services:
  web:
    image: 779846827025.dkr.ecr.ap-south-1.amazonaws.com/dev/entry_tracker:latest
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - backend_net

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - backend_net
    volumes:
      - db-data:/var/lib/mysql

networks:
  backend_net:

volumes:
  db-data:
