name: entryTracker

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Checkout App
      uses: actions/checkout@v2
      
    - name: Build the App
      run: docker build -t entry_tracker:${{ github.run_number }} .
      
    - name: Run Docker container
      run: docker run --name=entry_trackerb -p "5000:5000" -d entry_tracker:${{ github.run_number }}
      
    - name: Wait 
      run: sleep 5
      
    - name: CURL application
      run: curl http://localhost:5000 
  
    - name: test status code curl
      run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
          if [ $response_code -eq 200 ]; then
          echo "Service is up and running (Status code: $response_code)"
          exit 0
          else
          echo "Service check failed (Status code: $response_code)"
          exit 1
          fi
  package:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:  
    - name: package and run the whole application
      run: docker compose up
